### ISSUE TITLE
License is not specified

### ISSUE THREAD

**Issue by puiterwijk** [gtank/captcha-draft#3]
I was wondering what the licensing is on this idea/draft?

I know it's not done, but in how much would it be a problem if someone made derivative works or first trial implementations of this?

**Comment by gtank** [comment]
By all means, do what you want with it. I hadn't considered the licensing yet- do you have specific requests?

**Comment by puiterwijk** [comment]
I don't have any specific requests, I mainly wanted to be sure it's no problem if I happen to use ideas from this in my own projects to prevent problems for me or the company/communities I work for before reading it.
Thank you for the permission!
